name: "Rollback Action"
description: "Custom rollback script runner"

inputs:
  rollback_version:
    description: "Version to rollback to"
    required: true
  rollback_type:
    description: "Type of rollback (auto/manual)"
    required: false
  registry:
    description: "Registry to pull from"
    required: false
  last_success_sha:
    description: "Last successful commit SHA"
    required: false
  alert_webhook:
    description: "Slack/Discord alert webhook"
    required: false

runs:
  using: "composite"
  steps:
    - run: ./rollback.sh ${{ inputs.rollback_version }}
      shell: bash
