name: Rollback Demo

on:
  push:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run my rollback action
        uses: ./   # refers to action.yml in root
        with:
          rollback_version: "v1.0.0"
